const mainTypes = {
  DO_SOMETHING: 'DO_SOMETHING',
  WRITE_PRODUCT_LIST: 'WRITE_PRODUCT_LIST',
  PRODUCT_LIST_REQUESTED: 'PRODUCT_LIST_REQUESTED',
  WRITE_ORDER_LIST: 'WRITE_ORDER_LIST',
  ORDER_LIST_REQUESTED: 'ORDER_LIST_REQUESTED',
  ADD_TO_CART: 'ADD_TO_CART',
  COUNT_CART: 'COUNT_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
  SET_FILTER: 'SET_FILTER',
  EMPTY_THE_CART: 'EMPTY_THE_CART',
};

export default mainTypes;
