const mainTypes = {
  DO_SOMETHING: 'DO_SOMETHING',
  WRITE_PRODUCT_LIST: 'WRITE_PRODUCT_LIST',
  PRODUCT_LIST_REQUESTED: 'PRODUCT_LIST_REQUESTED',
  ADD_TO_CART: 'ADD_TO_CART',
  REMOVE_FROM_CART: 'REMOVE_FROM_CART',
};

export default mainTypes;
